### ISSUE TITLE
how to export onnx from lidar-bonnetal?

### ISSUE THREAD

**Issue by nicetaker** [Natsu-Akatsuki/RangeNet-TensorRT#20]
请问一下，怎样才可以从 https://github.com/PRBonn/lidar-bonnetal 里面导出跟您的工程一样的onnx呢？

**Comment by nicetaker** [comment]
请问步骤二是指深度学习链接搭建的那个步骤吗？那个链接404了。

我可能前面没有表达清楚，我想问的是如何从pytorch 工程导出和本工程一样的onnx ？

**Comment by nicetaker** [comment]
> https://github.com/Natsu-Akatsuki/RangeNetTrt8?tab=readme-ov-file#install 参考步骤 2

请问步骤二是指深度学习链接搭建的那个步骤吗？那个链接404了。

我可能前面没有表达清楚，我想问的是如何从pytorch 工程导出和本工程一样的onnx ？

**Comment by Natsu-Akatsuki** [comment]
1. ![image](https://github.com/user-attachments/assets/40405eff-8317-4d6b-86ee-60316491f702)
2. 我这边直接用的是原仓库（https://github.com/PRBonn/lidar-bonnetal ）提供的 onnx 文件，他怎么从 pytorch 模型转换为 onnx 模型不在当前仓库讨论范围

**Comment by nicetaker** [comment]
> 1. ![image](https://github.com/user-attachments/assets/40405eff-8317-4d6b-86ee-60316491f702)
> 
> 2. 我这边直接用的是原仓库（https://github.com/PRBonn/lidar-bonnetal ）提供的 onnx 文件，他怎么从 pytorch 模型转换为 onnx 模型不在当前仓库讨论范围

好的！谢谢您的回复
